theme: jekyll-theme-minimal
title: Dr. Patrick Feuerstein
description: My personal Homepage
#logo: [Location of the logo]
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]

defaults:
  -
    scope:
      path: ""

    values:
      menu1: Lebenslauf
      menu1url: "https://patrickfeuerstein.github.io/cv.html"
      menu2: Lehrportfolio
      menu2url: "https://patrickfeuerstein.github.io/teaching.html"
      menu3: Publikationen
      menu3url: "https://patrickfeuerstein.github.io/publications.html"
      img: Mein Bild
      img_url: "https://patrickfeuerstein.github.io/assets/me.jpg"
